export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    SORT_PRODUCT_BY_CATEGORY: "SORT_PRODUCT_BY_CATEGORY",
    SORT_PRODUCT_BY_PRICE: "SORT_PRODUCT_BY_PRICE",
}